version: '3.9'

services:
  microskel:
    build:
      context: microskel
    image: microskel

  consul-server:
    image: progrium/consul
    expose:
      - 8300
      - 8301
      - 8301/udp
      - 8302
      - 8302/udp
      - 8400
    ports:
      - "8500:8500"
    networks:
      siemens:
        ipv4_address: 10.10.10.2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
    command: "-server -bootstrap -ui-dir /ui -advertise 10.10.10.2"

  consul-agent:
    image: progrium/consul
    expose:
      - 8300
      - 8301
      - 8301/udp
      - 8302
      - 8302/udp
      - 8400
      - 8500
    networks:
      siemens:
        ipv4_address: 10.10.10.3
    depends_on:
      consul-server:
        condition: service_started
    command: "-advertise 10.10.10.3 -join 10.10.10.2"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    networks:
      siemens:
        ipv4_address: 10.10.10.4
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    depends_on:
      elasticsearch:
        condition: service_started
    ports:
      - "5601:5601"
    networks:
      siemens:
        ipv4_address: 10.10.10.5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 70M

  logstash-agent:
    image: docker.elastic.co/logstash/logstash:7.15.2
    expose:
      - 51515
    depends_on:
      kibana:
        condition: service_started
    networks:
      siemens:
        ipv4_address: 10.10.10.6
    command: "-e \"input { tcp { port => 51515 codec => json } } output { elasticsearch { hosts => 'http://10.10.10.4:9200' } } \""
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M

  service-one-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_USER=keyvalue
      - MYSQL_PASSWORD=abc123
      - MYSQL_DATABASE=keyvalue
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 20s
      retries: 5
      timeout: 5s
      start_period: 30s
    expose:
      - 3306
    networks:
      siemens:
        ipv4_address: 10.10.10.7
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    volumes:
      - dbdata_events:/var/lib/mysql

  service-events:
    build: service_events
    depends_on:
      consul-agent:
        condition: service_started
      logstash-agent:
        condition: service_started
      service-one-db:
        condition: service_healthy
      microskel:
        condition: service_started
    environment:
      - MICROSERVICE_NAME=service-events
      - MICROSERVICE_HOST=service-events
      - MICROSERVICE_PORT=5000
      - MICROSERVICE_DEBUG=True
      - CONSUL_CHECK_INTERVAL=20s
      - CONSUL_CHECK_TIMEOUT=10s
      - CONSUL_HOST=consul-agent
      - CONSUL_PORT=8500
      - LOGSTASH_AGENT_HOST=logstash-agent
      - LOGSTASH_AGENT_PORT=51515
      - LOGSTASH_ENABLED=True
      - MICROSERVICE_DB_URI=mysql://keyvalue:abc123@service-one-db/keyvalue
      - USE_DB=True
    networks:
      siemens:
        ipv4_address: 10.10.10.15
    ports:
      - "8085:5000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M

  redis-db:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=yourpassword
    networks:
      siemens:
        ipv4_address: 10.10.10.8
    ports:
      - "6380:6379"
    volumes:
      - dbdata_weather:/data

  service-gateway:
    build: service_gateway
    depends_on:
      - consul-agent
      - logstash-agent
      - microskel
    environment:
      - MICROSERVICE_NAME=service_gateway
      - MICROSERVICE_HOST=service-gateway-1
      - MICROSERVICE_PORT=5000
      - MICROSERVICE_DEBUG=True
      - CONSUL_CHECK_INTERVAL=20s
      - CONSUL_CHECK_TIMEOUT=10s
      - CONSUL_HOST=consul-agent
      - CONSUL_PORT=8500
      - LOGSTASH_AGENT_HOST=logstash-agent
      - LOGSTASH_AGENT_PORT=51515
      - LOGSTASH_ENABLED=True
      - MICROSERVICE_DB_URI=mysql://
      - USE_DB=False
    networks:
      siemens:
        ipv4_address: 10.10.10.20
    ports:
      - "8082:5000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M

  service-two-1:
    build: service_two
    depends_on:
      microskel:
        condition: service_started
      consul-agent:
        condition: service_started
      logstash-agent:
        condition: service_started
      service-one-db:
        condition: service_started
    environment:
      - MICROSERVICE_NAME=service_two
      - MICROSERVICE_HOST=service-two-1
      - MICROSERVICE_PORT=5000
      - MICROSERVICE_DEBUG=True
      - CONSUL_CHECK_INTERVAL=20s
      - CONSUL_CHECK_TIMEOUT=10s
      - CONSUL_HOST=consul-agent
      - CONSUL_PORT=8500
      - LOGSTASH_AGENT_HOST=logstash-agent
      - LOGSTASH_AGENT_PORT=51515
      - LOGSTASH_ENABLED=True
      - USE_DB=False
    networks:
      siemens:
        ipv4_address: 10.10.10.12
    ports:
      - "8081:5000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M

  service-weather:
    build: service_weather
    depends_on:
      microskel:
        condition: service_started
      consul-agent:
        condition: service_started
      logstash-agent:
        condition: service_started
      redis-db:
        condition: service_started
    environment:
      - MICROSERVICE_NAME=service_weather
      - MICROSERVICE_HOST=service-weather
      - MICROSERVICE_PORT=5000
      - MICROSERVICE_DEBUG=True
      - CONSUL_CHECK_INTERVAL=20s
      - CONSUL_CHECK_TIMEOUT=10s
      - CONSUL_HOST=consul-agent
      - CONSUL_PORT=8500
      - LOGSTASH_AGENT_HOST=logstash-agent
      - LOGSTASH_AGENT_PORT=51515
      - LOGSTASH_ENABLED=True
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_PASSWORD=yourpassword
      - USE_REDIS=True
    networks:
      siemens:
        ipv4_address: 10.10.10.22
    ports:
      - "8086:5000"

volumes:
  esdata:
  dbdata_events:
  dbdata_weather:

networks:
  siemens:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
